// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlvwehzqjtzoishzdqys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsdndlaHpxanR6b2lzaHpkcXlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4OTQ3MDgsImV4cCI6MjA1MjQ3MDcwOH0.jams4MGWQkuy95SfnaUe51HUO2LOk42v_g4BOvFpr4E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);